### ISSUE TITLE
createCollectionFormSimple Usage

### ISSUE THREAD

**Issue by Raistlfiren** [ibrows/IbrowsXeditableBundle#3]
Is createCollectionFormSimple() supposed to be used in conjunction with forms that have collections contained in them? It doesn't look like createFormFromRequest() handles forms with collections. Is there a reason why createCollectionFormSimple() takes in $data and $currentObject? It seems like they are both supposed to be the data of the form. Am I missing something?

Thanks!

Ratty

**Comment by Raistlfiren** [comment]
Am I also correct that it doesn't support an array collection (one to many) or (many to one) relationship on form collection?

**Comment by Gladhon** [comment]
You've right, the default FormMapper does not support collections it self. But it should be run, if its possible to add items in the x-editable modal. We never used it that way, but if you try it, your questions are welcome.

And yes, createCollectionFormSimple is there for support collections, but not in the same way. You have to add Actionsroutes to add/remove/edit your child objects.

Here is an example with a Person-Object with many Telephonenumbers ( collection )

Controller
 ```php
$this->get('ibrows_xeditable.mapper.factory')->createCollectionFormSimple('person_telephone_number', new PersonType(), $person, null, $request)
 ```
View

```php
{{ xedit_inline_render(telephoneNumberXeditables, 'telephoneNumbers', {},  {}) }}
```


Controller Child
 ```php
    public function xedittelephonenumberAction(TelephoneNumber $telephoneNumber, Request $request)
    {
        $telephoneNumberXeditable = $this->get('ibrows_xeditable.mapper.factory')->createCollectionFormSimple('person_telephone_number', new PatientType(), null, $telephoneNumber, $request);

        if ($request->isMethod('POST')) {
            if (($response = $telephoneNumberXeditable->handleRequest($request)) instanceof Response) {
                return $response;
            }
            $telephoneNumber = $response;
            $em = $this->getManagerForClass($telephoneNumber);
            $em->persist($telephoneNumber);
            $em->flush();
            return $this->redirectToForwardRoute($request);
        }
        return new Response($telephoneNumberXeditable->renderXeditable($request->get('path')));
    }
    public function deletetelephonenumberAction(TelephoneNumber $telephoneNumber, Request $request)
    {
        if ($request->isMethod('POST')) {
            $em = $this->getManagerForClass($telephoneNumber);
            $em->remove($telephoneNumber);
            $em->flush();

            return $this->redirectToForwardRoute($request);
        }

        return new Response($this->translate('delete.confirm'));
    }

    public function createtelephonenumberAction(Person $parent, Request $request)
    {
        $telephoneNumberXeditable = $this->get('ibrows_xeditable.mapper.factory')->createCollectionFormSimple('person_telephone_number', new PatientType(), null, $telephoneNumber, $request);

        if ($request->isMethod('POST')) {
            if (($response = $telephoneNumberCreateXeditable->handleRequest($request)) instanceof Response) {
                return $response;
            }

            /** @var TelephoneNumber $response */
            $parent->addTelephoneNumber($response);
            $em = $this->getManagerForClass($parent);
            $em->persist($parent);
            $em->flush();

            return $this->redirectToForwardRoute($request);
        }

        return new Response($telephoneNumberCreateXeditable->renderXeditable($request->get('path')));
    }
 ```

**Comment by Raistlfiren** [comment]
I am somewhat confused about your example. It seems as though it would work for my instance since you are collecting many telephone numbers. Building on your example, would this be the correct way you setup your Parent/Child form and entity?

```
    //Person entity...
    class Person extends ... {
       /**
     * @ORM\OneToMany(targetEntity="Test\Bundle\Person", mappedBy="person")
     * @ORM\JoinColumn(name="id", referencedColumnName="id")
     **/
    private $numbers;

    //Person Type
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numbers', 'collection', array(
                'type' => new NumbersType(),
                'options' => array('required' => FALSE)
            ));
    }
   public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Person'
        ));
    }

   //Numbers Type
       public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('number');
    }
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Number'
        ));
    }

The reason I ask is because I keep on running into errors attempting to do this. "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Number could not be converted to string")"

Which it obviously means that the form is getting the whole class value - Number, and not the string value. I noticed that your parameters are different too. In your first example it has the form values as the $data instead of the $currentObject. In the controller methods it is reversed. If I change my createCollectionSimple call to $data = NULL and $currentObject = Person Entity, I get a mapping error for my data_class. Which is fine, I change the data_class for NumberType to NULL and the error is "An exception has been thrown during the rendering of a template ("The form's view data is expected to be of type scalar, array or an instance of \ArrayAccess, but is an instance of class Person".

I render the form exactly how you have it in your example. 

Are you iterating on the AbstractFormXeditableMapper object some how in the TWIG view? For example -

```
     {% for number in form.numbers %}
                        {{ xedit_inline_render(number, 'telephonenumber', {}, {}) }}
                    {% endfor %}

**Comment by Gladhon** [comment]
For me, your target-entity annotation in your Person-Entity looks wrong.  I think there have to be something like: Test\Bundle\Number 
All other things look like i would expect it. I hope changing target-entity would solve your problems.

To your twig question. Iterating is not needed there, the formmapper knows how to iterate. 
The xedit_inline_render function first take a Formmapper and second the form-path. In your case, it could look like that:
```
{{ xedit_inline_render(collectionFormSimple, 'numbers', {}, {}) }}
```

**Comment by Raistlfiren** [comment]
@Gladhon Thanks for the input. I did have my form entities like that, Test\Bundle\Number, but I was just displaying 'Number' for ease. I am going to work on some tests for the bundle in order to try to troubleshoot my issue. You have been very helpful. :+1:

**Comment by Raistlfiren** [comment]
I decided to revisit this issue, and I still keep on hitting a brick wall. I decided to make tests as well. Please try the functional tests that I created to test the collectionFormSimple(). https://github.com/Raistlfiren/IbrowsXeditableBundle

The relevant tests are in the standalonetestbundle - https://github.com/Raistlfiren/IbrowsXeditableBundle/blob/master/Tests/StandaloneTestBundle/Tests/Controller/FormControllerTest.php#L39

I keep on running into the error - 

```php
An exception has been thrown during the rendering of a template ("Object of class Ibrows\XeditableBundle\Tests\StandaloneTestBundle\Entity\Number could not be converted to string") in IbrowsXeditableBundle::xeditableform_delete.html.twig at line 1. 
```

Is this the correct usage example?

**Comment by Gladhon** [comment]
Thx for error-report, have you tried allready adding a __toString() method to Number ? What's happen then?

**Comment by Raistlfiren** [comment]
I add a method - 

```php

public function __toString()
    {
        return $this->getNumber();
    }

```

This technically works, but the remove button doesn't really work. It displays the following when remove is clicked - 
![screen shot 2015-08-25 at 8 38 41 am](https://cloud.githubusercontent.com/assets/234712/9467985/cf2a02be-4b04-11e5-91eb-bd3439fc4b3f.png)]

(The screenshot is from the live data, not the test result. Alias is the equivalent of Number in this example.)

The biggest problem as well, would be rendering multiple fields. For example, say I have a person with many addresses, and the address type contains address, city, state fields... There isn't a great way of rendering it. It would be nice to render the items from a collection individually like symfony does. Ex.: 

```php
{{ xedit_inline_render(form, 'addresses.address') }}
```

**Comment by Raistlfiren** [comment]
It does seem like I am kind of reaching outside of the scope of the project. I can start working on my own PR, and send it in. I just wanted to make sure I wasn't doing something wrong or missing something based on the example you gave me.

**Comment by Gladhon** [comment]
You can use a template option:

```
 {{ xedit_inline_render(form, 'addresses', {}, {'template': 'IbrowsAppBundle:xedit:addresscollection.html.twig'}) }}
```

Where you can extends the bundle template or do your complete own

```
{% extends '@IbrowsXeditable/xeditablecollection.html.twig' %}

**Comment by Raistlfiren** [comment]
Nice, I think I might have it working now!
