### ISSUE TITLE
Example: Variable "xeditableFormMapper" does not exist

### ISSUE THREAD

**Issue by eongering** [ibrows/IbrowsXeditableBundle#4]
When trying to implement the given example from the documentation I keep getting a Twig runtime error:

Variable "xeditableFormMapper" dows not exist in IbrowsXeditableBundle::xeditableform.html.twig at line 5.

I followed the Install and setup from the documentation without any errors and rewrote the example to fit my bundle, which is very simple in this case.

I have an entity called "enquiry" with some data fields (eg. datetimeOpened and datetimeClosed).
In the EnquiryController I created a public function called xeditAction:

/**
    * @Route("/{enquiry}/xedit/", name="enquiry_xedit")
    * @param Enquiry $enquiry
    * @param Request $request
    * @return Response|\Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response|void
    */
    public function xeditAction(Enquiry $enquiry, Request $request)
    {
        $factory = $this->get('ibrows_xeditable.mapper.factory');
        
        $xeditableFormMapper = $factory->createFormFromRequest(
            'enquiry_xedit', //target route where data would be sent after submit
            array('enquiry' => $enquiry->getId()), // parameters  for the target route
            $request, // request to get information about the current view, to find forward paramters
            new EnquiryType(),  // a form type with some fields
            $enquiry, // form data for the form type
            array('validation_groups' => array('edit_enquiry')) // form options for the form type
        );

        if ($request->isMethod('POST')) {
            if (($response = $xeditableFormMapper->handleRequest($request)) instanceof Response) {
                return $response;
            }

            $em = $this->getManagerForClass($enquiry);
            $em->persist($enquiry);
            $em->flush();

            // after success redirect to view, so frontend can be refreshed
            return $this->redirectToForwardRoute($request, 'GET');
        }
        // get back view of the handled form, to display error messages
        return new Response($xeditableFormMapper->renderXeditable($request->get('path')));
   }

and I put the rewritten twig functions in xeditableform.html.twig:

    {{ xedit_inline_render(xeditableFormMapper, 'datetimeOpened', {'data-emptytext': 'datetimeOpened'|trans}) }}
    {{ xedit_inline_render(xeditableFormMapper, 'datetimeClosed', {'data-emptytext': 'datetimeClosed'|trans}) }}

But when I try the route (eg. /enquiry/1/xedit), I keep getting the message:
"Variable "xeditableFormMapper" does not exist in IbrowsXeditableBundle::xeditableform.html.twig at line 5
500 Internal Server Error - Twig_Error_Runtime"

Any ideas on this?

Thanks in advance and kind regards,

eongering

**Comment by Gladhon** [comment]
Ah I see. You have to use 2 actions.
First one is your default view, with your layout and so on. And in it theres just a xeditableFormMapper and these lines.
```
{{ xedit_inline_render(xeditableFormMapper, 'datetimeOpened', {'data-emptytext': 'datetimeOpened'|trans}) }}
{{ xedit_inline_render(xeditableFormMapper, 'datetimeClosed', {'data-emptytext': 'datetimeClosed'|trans}) }}
```
Then you should have an xeditAction ( as you have ) which just there to save the Form, Render errors etc. 
Ok ?

**Comment by prakashsinghgaur** [comment]
Hi.. @Gladhon can you elaborate more on the first action in which default view and layout will be covered.
I am having two actions 1) showAction and 2)xeditAction and one Twig template (edit.html.twig)

1) showAction:-

` /**
     * @Route("/actions/test/{id}", name="action_test")
     */
    public function showAction($id,Request $request){
        $action  = new Action();

        $factory = $this->get('ibrows_xeditable.mapper.factory');
        $xeditableFormMapper = $factory->createFormFromRequest(
       'action_xedit', //target route where data would be sent after submit
        array('action' => $action->getId()), // parameters  for the target route
        $request, // request to get information about the current view, to find forward paramters
        new ActionType(),  // a form type with a name and a firstName field
        $action, // form data for the form type
        array('validation_groups' => array('edit_action')) // form options for the form type
        );

        return $this->render('action/edit.html.twig', array(
                                            'xeditableFormMapper' => $xeditableFormMapper,
                                            'action' => $action,
            ));
    }`

and 2) xeditAction:-

`/**
     * @Route("/actions/{action}/xedit", name="action_xedit")
     * @param Action $action
     * @param Request $request
     * @return Response|\Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response|void
     */
    public function xeditAction(Action $action,Request $request){
    $factory = $this->get('ibrows_xeditable.mapper.factory');

        $xeditableFormMapper = $factory->createFormFromRequest(
                                    'action_xedit',
                                   // array('id' => $action->getId()),
                                     array('action' => $action->getId()),
                                            $request, 
                                             new ActionType(),
                                             $action
                                        );
 if ($request->isMethod('POST')) {
                if (($response = $xeditableFormMapper->handleRequest($request)) instanceof Response) {
                    return $response;
                }
            $em = $this‐>getManagerForClass($action);
            $em‐>persist($action);
            $em‐>flush();
            return $this‐>redirectToReferer();
}
        return new Response($xeditableFormMapper->renderXeditable($request->get('path')));
}
}`

and in my Twig template:-

`
{% extends 'base.html.twig' %}
{% block body %}

 {{ xedit_inline_render(xeditableFormMapper, 'actionDescription', {'data-emptytext': 'actionDescription'|trans}) }}

{% endblock %}`

Now when i visit actions/test/1  I can only see a blank page with the following html:-

`<a href="#" class="ibrowsXeditable" data-xeditable="" data-path="actionDescription" data-url="/tpms/web/mou/section2/actions//xedit?forwardRoute=action_test&amp;forwardRouteParams%5Bid%5D=4" data-type="ibrows_xeditable_form" id="xeditable_appbundle_action_actionDescription" maxlength="255" data-emptytext="actionDescription" data-form="<input type=&quot;text&quot; id=&quot;appbundle_action_actionDescription&quot; name=&quot;appbundle_action[actionDescription]&quot; required=&quot;required&quot; maxlength=&quot;255&quot; class=&quot;form-control&quot; />">
</a>`

and if I visit actions/1/xedit  it throws an error saying that **The controller must return a response (Object(Symfony\Component\BrowserKit\Response) given).**

So first please guide me what i am doing wrong in these actions, then what route should I visit from the above two controllers..

Many thanks
