### ISSUE TITLE
Version for symfony3

### ISSUE THREAD

**Issue by prakashsinghgaur** [ibrows/IbrowsXeditableBundle#6]
Hi.. 
Is this bundle only for symfony 2 not 3.x. If yes, then grateful if someone can suggest same bundle for 3.x

**Comment by Gladhon** [comment]
Currently yes, but we are open for any pull-request in this direction. In the future it might be also symfony3 compatible, but now we dont have time for that

**Comment by qtsd** [comment]
done with qtsd/IbrowsXeditableBundle@86e95deb0e3842f13c7c2c6dbec2cad3b7e585cc but not yet tested in all cases

**Comment by Gladhon** [comment]
looks not bad, but i don't think it works for symfony 2.x, so please change to  "symfony/symfony": "~3.0", and then, a pull request would be nice
